### ISSUE TITLE
Cannot get both home and system to build? 

### ISSUE THREAD

**Issue by mannp** [gvolpe/nix-config#13]
Firstly, thanks for putting this config out there, it's great for nix newbies like me to get started 👍🏻 

I am updating my config, to use some of your new updates around cachix :) but have got stuck with the following error;
```

❯ ./build.sh
No custom build option given. Building system and home.
Configured https://my-nixos.cachix.org binary cache in /home/local/.config/nix/nix.conf

/tmp/nix-shell-9590-0/rc: line 1: build_system: command not found
```

I can update home and system separately without issues -> ./build.sh home and ./build.sh system

Wondered if it was my error? 

Thanks in advance

**Comment by gvolpe** [comment]
The script was wrong, it should be fixed in https://github.com/gvolpe/nix-config/commit/be21dd291a9b55e6b0de077390c792fdc86f08c9
