### ISSUE TITLE
Typo in Dunst Config

### ISSUE THREAD

**Issue by hamzashahid-blit** [gvolpe/nix-config#20]
Hello,
I think I found a typo while looking through your config;
https://github.com/gvolpe/nix-config/blob/master/home/services/dunst/default.nix#L43
In Line 43, 48 and 53.
Where you say:
```
      urgency_low = {
        background = "#${base00}";
        forefround = "#${base05}";
        timeout = 4;
      };
      urgency_normal = {
        background = "#${base00}";
        forefround = "#${base05}";
        timeout = 4;
      };
      urgency_critical = {
        background = "#${base0A}";
        forefrond = "#${base0D}";
        frame_color = "#${base08}";
        timeout = 10;
      };
    };
```

See the "Foreground" Typo? Maybe I'm wrong and this isn't a typo, but I couldn't find any dunst option with that name. Thanks :)

Kind Regards,
Hamza

**Comment by gvolpe** [comment]
Thanks! Never noticed those :)

Fixed in https://github.com/gvolpe/nix-config/commit/f0e3b795df1252843e2f4224e5b86869a1477f0f

**Comment by hamzashahid-blit** [comment]
No problem!
