### ISSUE TITLE
Your GitHub notifications token seems to be checked in

### ISSUE THREAD

**Issue by mightyiam** [gvolpe/nix-config#5]
Maybe you feel it's not a risk.

**Comment by gvolpe** [comment]
WDYM? This file? https://github.com/gvolpe/nix-config/blob/master/home/secrets/github-notifications-token

**Comment by mightyiam** [comment]
Yes, that file. Isn't it a secret token? Can I read your GitHub notifications with it?

**Comment by gvolpe** [comment]
It's an encrypted file, you won't be able to use it.
